version: '3.7'

services:
  
  frontend:
    image: frontend12
    ports:
      - 5000:5000
    environment:
      - API_URL=http://localhost:8000

  backend:
    image: backend12  
    volumes:
      - ./logs.txt:/usr/app/logs.txt
    ports:
      - 8000:8000
    environment:
      - FRONT_URL=http://localhost:5000
